# Schema for the configuration files of the XHProf module.
xhprof.config:
  type: mapping
  label: 'XHProf configuration'
  mapping:
    xhprof_enabled:
      type: boolean
      label: 'XHProf enabled'
    xhprof_disable_admin_paths:
      type: boolean
      label: 'Disable profiling of admin pages'
    xhprof_interval:
      type: string
      label: 'The approximate number of requests between XHProf samples. Leave empty to profile all requests'
    xhprof_default_class:
      type: string
      label: 'Choose an XHProf runs class'
