# Schema for the configuration files of the XHProf module.
xhprof.config:
  type: mapping
  label: 'XHProf configuration'
  mapping:
    enabled:
      type: boolean
      label: 'XHProf enabled'
    interval:
      type: string
      label: 'The approximate number of requests between XHProf samples. Leave empty to profile all requests'
    storage:
      type: string
      label: 'Choose the XHProf storage class'
    exclude:
      type: string
      label: 'Path to exclude'
